Added "power outlets in the room" feature
feDann/AuleLiberePoliMi pull request #5
Opened 2022-03-15 17:47 UTC by frbuccoliero

I added this feature that displays a little plug emoji next to the rooms that have power outlets. My first approach was to make a request for each room and check in the html of the expanded view of the single room, but this approach ended up slowing the bot too much. This solution instead adds a little json file with the "id_aula" numbers of the rooms that have power outlets, conveniently generated by a little script I added. As I wrote there since we don't change power outlets every day you can just run this script every once and a while and will be fine. 

- Thx to @lorenzocavallero for the idea

2022-03-16 14:35 UTC, feDann commented on search/find_classrooms.py
> +        j.close()
redundant

2022-03-16 14:35 UTC, feDann commented on search/find_classrooms.py
> +                        info[buildingName][room]['powerPlugs'] = id_aula in rwp
should use a set instead of a list for performance

2022-03-16 14:36 UTC, feDann requested changes
can you upload a screenshot of the final result?

2022-03-17 21:30 UTC, frbuccoliero commented
Screenshot of the new feature as requested:

![image](https://user-images.githubusercontent.com/14348908/158898221-629feb1b-e206-42c0-92b3-35bc20e0b4d2.png)

2022-03-20 01:16 UTC, merged